version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    container_name: analytics-postgres
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    restart: always

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: analytics-producer
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKER: "kafka:9092"
      TOPIC_NAME: "incoming.user_activity"
      PORT: "8081"
    restart: always

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: analytics-consumer
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BROKER: "kafka:9092"
      TOPIC_NAME: "incoming.user_activity"
      WORKER_COUNT: "4"
      POSTGRES_CONN_STR: "postgres://analytics_user:analytics_password@postgres:5432/analytics_db?sslmode=disable"
    restart: always
